# https://tox.wiki/en/latest/config.html
[tox]
min_version = 4.22
env_list = ruff,black,mypy,docs,py

[gh]
python =
    3.13t = nodeps
    3.14  = nodeps
    3.14t = nodeps

[testenv]
dependency_groups =
    test
deps =
    asammdf>=6.0; platform_python_implementation=="CPython"
    msgpack~=1.1.0
    pywin32>=305; platform_system=="Windows" and platform_python_implementation=="CPython"
commands =
    pytest {posargs}
extras =
    canalystii
passenv =
    CI
    GITHUB_*
    COVERALLS_*
    PY_COLORS
    TEST_SOCKETCAN

[testenv:nodeps]
deps =

[testenv:lint]
base =
skip_install =
    true
dependency_groups =
    lint
[testenv:black]
base =
    lint
commands =
    black --check can doc examples test

[testenv:ruff]
base =
    lint
commands =
    ruff check can examples

[testenv:mypy]
base =
    lint
skip_install =
    false
commands =
    mypy can

[testenv:docs]
description = Build and test the documentation
basepython = py312
dependency_groups =
    docs
extras =
    canalystii
    gs-usb
    mf4
    remote
    serial
commands =
    python -m sphinx -b html    -Wan --keep-going doc build
    python -m sphinx -b doctest -W   --keep-going doc build

[pytest]
testpaths = test
addopts = -v --cov=can --cov-config=tox.ini --cov-report=lcov


[coverage:run]
# we could also use branch coverage
branch = False

[coverage:report]
# two digits after decimal point
precision = 3
show_missing = True
exclude_lines =
    # Have to re-enable the standard pragma, see https://coverage.readthedocs.io/en/coverage-4.5.1a/config.html#syntax
    pragma: no cover

    # Don't complain if non-runnable code isn't run:
    if __name__ == .__main__.:

    # Don't complain if tests don't hit defensive assertion code:
    raise NotImplementedError
